### ISSUE TITLE
Customize the clear search button

### ISSUE THREAD

**Issue by metalshanked** [m-wrzr/streamlit-searchbox#42]
Thanks for this amazing library!
had some quick questions around the clear button
1. Is there a way to make the clear button (the small X button) more prominent with colors, larger etc?
2. Is there a way to clear the input box from an external button?

**Comment by m-wrzr** [comment]
Thanks for the questions & input. 

1) I've added some more styling functionality with version `0.1.11`. There is now an option to select between different icons as well as adjusting some other styling related attributes, which wasn't possible before.

![Screenshot 2024-05-12 at 18 54 46](https://github.com/m-wrzr/streamlit-searchbox/assets/6058447/c7d9320c-6701-4800-9815-3ab33c105d67)

Code:

```python
style_overrides={
            "clear": {
                "width": 20,
                "height": 20,
               # default: circle-filled
               # other: cross 
               "icon": "circle-unfilled",
                "stroke-width": 2,
                "stroke": "red",
            },
}
```

2) Regarding clearing the searchbox externally, the easiest way to achieve this right now would be to either assign a new `key` to the component or otherwise overwrite the searchbox state as mentioned in this issue: https://github.com/m-wrzr/streamlit-searchbox/issues/36 - I'm also planning to add some external trigger functions for this usecase in the coming weeks. Hope that helps!

**Comment by metalshanked** [comment]
Thank much!  It is working great. One small observation is that the IDE linter shows an different expect different type than "dict" mentioned in the doc. 
It works fine though, will report if issues.

![image](https://github.com/m-wrzr/streamlit-searchbox/assets/57646596/654a3954-c938-4692-8452-c8decf79c0fc)

**Comment by m-wrzr** [comment]
Thanks for pointing it out, I've updated the type annotations 👍
