### ISSUE TITLE
searchbox options move other elements around (not positioned absolutely)

### ISSUE THREAD

**Issue by JoshElgar** [m-wrzr/streamlit-searchbox#46]
temporary workaround:

```
    css = """
    iframe[title="streamlit_searchbox.searchbox"] {
        position: absolute;
        z-index: 10;
    }
    """
    st.markdown(f"<style>{css}</style>", unsafe_allow_html=True)
```

**Comment by m-wrzr** [comment]
Thanks for providing the workaround, this is afaik the only way to position it absolutely since the iFrame itself can't escape its bounds. I'll add it to the searchbox with some additional blocks to reserve space. It's still a bit problematic, since this will always apply to all searchboxes, but there is also no other way of targeting. Do you want me to add some attribution?
